version = 1

exclude_patterns = [
  "vendor/**",
  "public/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/akshit-deepsource/fiber"
  cyclomatic_complexity_threshold = "low"
